### ISSUE TITLE
Fix performance issues reported by PageSpeed Insights

### ISSUE THREAD

**Issue by DainialPadraig** [CodeForTucson/codefortucson-site#34]
Running PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/) on our webpage reveals a number of performance and portability issues that should be addressed.

**Comment by meiqimichelle** [comment]
This one might have to wait a little bit. Really I'd like to re-write the entire site because we pulled over many performance and structure issues from the DC version of the site, but I'm not sure when I'll have time :( I mean to say -- the DC version is totally fine for a volunteer org, as is our site, but...as always...could be improved :)

Either way, glad to have this in an issue for future work.

**Comment by DainialPadraig** [comment]
Some of it is low-hanging fruit and some might be difficult to do anything
about (like needing the Jekyll scripts in the header, which is non-optimal
from a performance standpoint). Also probably duplicates some of the other
issues in GitHub (like needing the image loading issues.) Maybe we just
make this part of our workflow when updating the website.

Many of these issues would be good things to hack on at future hack nights
and would help share some of the ownership of the website.

**Comment by dmsnell** [comment]
This issue was moved to CodeForTucson/codefortucson.org#1

**Comment by dmsnell** [comment]
Closing in favor of splitting into separate issues under the "Optimize Public Site" milestone
