### ISSUE TITLE
Code: Website refactor to Angular 1.x for calendar widget

### ISSUE THREAD

**Issue by johnazre** [CodeForTucson/codefortucson-site#73]
I just spoke to Dan and he had mentioned that you guys were looking to maybe put a calendar widget on the website. I know a couple of groups of people who have done that using Angular 1.x without much trouble (famous last words, right?). React and Angular 2 are also options, but having not researched calendar solutions, I'm not sure what that would involve at this point. 

This is in relation to #46.

**Comment by johnazre** [comment]
Here's a basic, functional Angular 1.x refactor. https://github.com/johnazre/cftNgRefactor

**Comment by meiqimichelle** [comment]
Hi @johnazre ! The story got a bit confused through the chain, I think! We actually intentionally moved off supporting our own calendar because of the time it takes to maintain it (not much, but still) when Meetup does this for us. So, we're pretty happy with just linking over to our Meetup schedule of events for now.

I'm sorry I didn't catch this before you started work 😢  We'll have better-defined issues on the website refactor once the [content](https://github.com/CodeForTucson/codefortucson-site/issues/63) and [design work](https://github.com/CodeForTucson/codefortucson-site/issues/64) get off the ground. We're hoping to make progress over the next few months (slowly but surely, that's our motto 😉  ).

If you'd like to pitch in on an active project instead of waiting for us to get our designing in order, I believe [CommunityShare](https://github.com/communityshare/communityshare) has some open issues that need resolving!

**Comment by johnazre** [comment]
No worries. haha. It didn't take long. I'll go check out CommunityShare, then. Thanks! :)

**Comment by dmsnell** [comment]
Closing due to above discussion.
